name: Publish Binaries

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: headless tests
        run: ./gradlew nonGuiTest
      - name: GUI tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew guiTest
      - name: Build Spring Boot Jar
        run: ./gradlew bootJar
      - name: Upload Jar
        uses: actions/upload-artifact@v2
        with:
          name: boot-jar
          path: |
            build/libs/*.jar
            !build/libs/*-plain.jar
  generate:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.jar'    